# Default values for channelit-report service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: Always

app:
  port: 80
  # Shared environment variables within Channel IT
  commonEnv:
    - redis_url
    - redis_password
    - gateman_key
    - db_host
    - db_port
    - db_servicename
    - db_username
    - db_password
    - encrypt_secret
    - encrypt_secret_iv
    
  # Environment variables specific to this service
  env:
    - app_name
    - app_env
    - app_key
    - log_channel
    - log_level
    - gateway_service_url
    - gateway_service_api_version
    - subscription_service_url
    - subscription_service_api_version
    - aws_bucket
    - aws_default_region
    - aws_access_key_id
    - aws_secret_access_key

  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 250Mi

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
