apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "channelit-utility.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "channelit-utility.name" . }}
    helm.sh/chart: {{ include "channelit-utility.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "channelit-utility.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "channelit-utility.name" . }}-worker
        app.kubernetes.io/instance: {{ .Release.Name }}-worker
      annotations:
        updatedAt: {{ now | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # ports:
          #   - name: workerhttp
          #     containerPort: {{ .Values.worker.port }}
          #     protocol: TCP
          env:
            - name: CONTAINER_MODE
              value: worker
            - name: WORKER_COMMAND
              value: "php artisan queue:work sqs-fifo --sleep=3 --tries=3 --max-time=3600"
            - name: SERVICE_NAME
              value: {{ .Chart.Name }}-worker
            {{- range $env := .Values.app.commonEnv }}
            - name: {{ $env | upper }}
              valueFrom:
                secretKeyRef:
                  name: channelit-common
                  key: {{ $env }}
            {{- end }}
            {{- range $env := .Values.app.env }}
            - name: {{ $env | upper }}
              valueFrom:
                secretKeyRef:
                  name: channelit-utility
                  key: {{ $env }}
            {{- end }}
            {{- range $env := .Values.worker.env }}
            - name: {{ $env | upper }}
              valueFrom:
                secretKeyRef:
                  name: channelit-utility-worker
                  key: {{ $env }}
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: workerhttp
          #   initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
