# Default values for channelit-gateway service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: Always

app:
  port: 80
  # Shared environment variables within Go Money
  commonEnv:
    - amqp_url
    - redis_url
    - redis_password
    - gateman_key
  # Environment variables specific to this service
  env:
    - jwt_secret
    - default_otp

  resources:
    limits:
      cpu: 350m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi

worker:
  port: 4003
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 230Mi
    requests:
      cpu: 100m
      memory: 200Mi

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
